name: Build AMI Workflow

on:
  push:
    branches: ["main"]

env:
  PRODUCT_VERSION: "1.9.4" # or: "latest"

jobs:
  ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get -y install zip

      - name: Create a zip archive
        run: |
          zip -r ./webapp.zip ./app/
          ls

      - name: Verify Zip File Creation
        run: sudo ls -l ./webapp.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Packer Init
        run: |
          pwd
          ls
          packer init ./app/packer/aws-us-east-1.pkr.hcl

      - name: Build AMI
        run: packer build ./app/packer/aws-us-east-1.pkr.hcl
