name: Packer Validation Workflow

on:
  pull_request:
    branches: [ "main" ]
    # types:
    #   - "opened"
    # paths:
    #   - 'packer/aws-us-east-1.pkr.hcl' 

env:
  PRODUCT_VERSION: "1.9.4" # or: "latest"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PRODUCT_VERSION }}

      - name: Packer fmt and validate
        run: |
         packer fmt ./packer/aws-us-east-1.pkr.hcl
         packer validate ./packer/aws-us-east-1.pkr.hcl