name: Node.js CI with mysql

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  PRODUCT_VERSION: "1.9.4" # or: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 1998@Pupss
          MYSQL_DATABASE: assignment3
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    defaults:
       run:
         working-directory: ./app/

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './app/package-lock.json'

    - name: Install Dependencies
      run: npm install

    - name: Run Integration Tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: 1998@Pupss
        DB_NAME: assignment3
      run: |
            npm run build --if-present
            npm test

    - name: Install zip
      run: sudo apt-get -y install zip

    - name: Create a zip archive
      run: |
        zip -r ../webapp.zip ../app/
        zip -r ./packer/webapp.zip ../app/
        cd ..
        ls

    - name: list dir
      run: |
        ls

    - name: list dir
      run: |
        ls

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup `packer`
      uses: hashicorp/setup-packer@main
      id: setup
      with:
        version: ${{ env.PRODUCT_VERSION }}

    - name: Packer Init
      run: |
         pwd
         ls
         packer init ./packer/aws-us-east-1.pkr.hcl

    - name: Build AMI
      run: packer build ./packer/aws-us-east-1.pkr.hcl
