name: Node.js CI with mysql

on:
  push:
    branches: [ "main", "assignment3" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 1998@Pupss
          MYSQL_DATABASE: assignment3
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    defaults:
       run:
         working-directory: ./

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set Up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm install

    - name: Run Integration Tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USER: root
        DB_PASSWORD: 1998@Pupss
        DB_NAME: assignment3
      run: |
            npm run build --if-present
            npm test
            echo "Integration tests have completed."  # Add a custom message to indicate test completion
      continue-on-error: true  # Continue the workflow even if the tests fail

    - name: Check Test Completion
      run: |
        test_status=$(echo "${{ steps.integration_tests.outcome }}" | tr '[:upper:]' '[:lower:]')
        if [[ "$test_status" == "success" ]]; then
          echo "Integration tests were successful. Continue with the workflow."
        else
          echo "Integration tests failed or were incomplete. Stop the workflow."
          exit 1  # Exit the workflow with an error code
        fi
